### ISSUE TITLE
issues with requirements.txt - xgboost n/a for windows, scikit_learn 

### ISSUE THREAD

**Issue by creditquant** [KxSystems/mlnotebooks#5]
doing conda install --file requirements.txt as suggested in the readme.md leads to two problems for me running on Windows 10 (64-bit):

"PackagesNotFoundError: The following packages are not available from current channels:
  - xgboost
  - scikit_learn==0.19.1   

"

https://anaconda.org/conda-forge/xgboost shows that xgboost is not available for Windows
One solution might be to use py-xgboost instead of xgboost

https://anaconda.org/anaconda/scikit-learn suggests that requirements.txt should probably have said "scikit-learn" rather than "scikit_learn" ... indeed after making that change in requirements.txt scikit-learn disappeared from the error message.

**Comment by cmccarthy1** [comment]
Thanks for the message. I've taken a look at this and will update the requirements and README.md to account for the changes. 

An instruction to `conda install -c anaconda py-xgboost` which will suffice for both python and windows within the README.md (from what I have read this can't be pip installed so it wouldn't be suitable to remain within the requirements.txt) and fix to scikit-learn within the requirements.txt file should solve the issues. These changes should be made in the coming days once testing on a windows machine has been completed.
